import { Text } from "@/design-system/components/Text";
import { useTheme } from "@/design-system/ThemeProvider";
import Ionicons from "@expo/vector-icons/Ionicons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

export default function TermsOfServiceScreen() {
  const { colors } = useTheme();

  return (
    <SafeAreaView
      style={[styles.container, { backgroundColor: colors.background }]}
      edges={["top", "left", "right"]}
    >
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color={colors.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={[styles.lastUpdated, { color: colors.textTertiary }]}>
          Last updated: March 2026
        </Text>

        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Welcome to Lumora. By using our app, you agree to these Terms of Service. Please read them carefully.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          1. Service Description
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Lumora is a language learning platform that provides structured lessons, AI-powered conversation practice, and pronunciation feedback. The app is designed to help users learn new languages through interactive content.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          2. Free Trial
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We offer a 7-day free trial that gives you full access to all premium features. No payment information is required to start a trial. You will not be charged during or after the trial period. When the trial expires, premium features will become locked until a paid subscription is available.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          3. User Accounts
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          You are responsible for maintaining the security of your account credentials. You must provide accurate information when creating your account. You may delete your account at any time from the Profile screen.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          4. User Conduct
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          You agree not to misuse the service, attempt to gain unauthorized access to our systems, use the app for any unlawful purpose, or interfere with other users' experience. We reserve the right to suspend or terminate accounts that violate these terms.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          5. Intellectual Property
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          All content in the app — including lessons, curriculum materials, UI design, and branding — is owned by Lumora and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works from our content without written permission.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          6. AI-Generated Content
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Some content in the app, including conversation practice and lesson explanations, is generated by AI language models. While we strive for accuracy, AI-generated content may occasionally contain errors. It should not be relied upon as a sole reference for language accuracy.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          7. Limitation of Liability
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          Lumora is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the app. Our total liability is limited to the amount you have paid us, if any.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          8. Changes to These Terms
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          We may update these Terms of Service from time to time. Continued use of the app after changes constitutes acceptance of the updated terms. We will notify you of material changes through the app.
        </Text>

        <Text style={[styles.sectionTitle, { color: colors.text }]}>
          9. Contact Us
        </Text>
        <Text style={[styles.body, { color: colors.textSecondary }]}>
          If you have questions about these Terms of Service, please contact us at brendan.milton1211@gmail.com.
        </Text>

        <View style={styles.bottomSpacing} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  headerSpacer: {
    width: 40,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  lastUpdated: {
    fontSize: 13,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    marginTop: 24,
    marginBottom: 8,
  },
  body: {
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },
  bottomSpacing: {
    height: 40,
  },
});
